### ISSUE TITLE
Hard Drive Errors in NitrOS-9

### ISSUE THREAD

**Issue by pahandav** [VCCE/VCC#97]
Ever since 2.1.0b, copy files to hard drives in NitrOS-9 outputs: copy: can't open <filename> - ERROR #247

I've only tested it when copying files over when trying to install NitrOS-9 to an HD. Based on file analysis, it seems to be cutting off the ends of the files it's writing, or not writing them at all, if the files are small enough. Needless to say, NitrOS-9 installed in this way is unbootable. Seeing as 2.1.0c is when support for a second hard drive was added, the bug probably has something to do with that code.

**Comment by ejaquay** [comment]
First debug step check ident -m  emudsk  module crc should be CF433F
edition 06

**Comment by pahandav** [comment]
The install disk I used gives me that CRC when i run that command. I can't check the CRC on the hard drive because that doesn't boot.

**Comment by ejaquay** [comment]
Seek error is pretty generic.  I would try a a different  vhd.  I have
heard no other reports of simular nature,  vhds seem to have been pretty
solid with latest emudsk driver.

**Comment by pahandav** [comment]
Well, these are VHDs I made up with my own compiled from scratch install disks. I've copied a couple files from a drive installed under 2.1.0b and the same files from a drive installed under 2.1.0.5. Looking at them in a hex editor shows that stuff is being cut off, or not being copied at all. The attached file has those files, the VHDs installed under 2.1.0b and 2.1.0.5, and the install disks I used
[VHD Files and Install Disks.zip](https://github.com/VCCE/VCC/files/8536244/VHD.Files.and.Install.Disks.zip)
.

**Comment by ejaquay** [comment]
If the Vcc version was the cause of your problem I think we would have
heard other reports by now.  Truncated files and seek errors sound like VHD
file corruption.

**Comment by ejaquay** [comment]
I have been able to recreate the issue, it seems newer versions of vcc are
unable to format hard drives properly.   Apparently not many people have
been formatting from os9, they have just been copying an empty formatted
vhd when they wanted a new one.  I will look into it.

**Comment by ejaquay** [comment]
Shortly after the second hard drive was added we started getting errors
copying files between the drives.  They turned out to be caused by a bug in
emudsk, which is why I first asked about it;s version.  However as part of
the debug effort a check was added in Vcc to return an error if an attempt
is made to read past the end of an VHD.   This check is why Vcc can no
longer format an empty file.

**Comment by ejaquay** [comment]
fixed commit 382e2bc

**Comment by ejaquay** [comment]
A Vcc build containing this fix can be found at h
https://github.com/ejaquay/VCC/releases/download/2.1.0.6-beta-382e2bc/vcc2.1.0.6-beta-382e2bc.zip

**Comment by pahandav** [comment]
I'll try to test that out before the end of the weekend. Thanks.

**Comment by pahandav** [comment]
I tested it, and the problem persists. The exact same thing happens, unfortunately.

**Comment by BGPierce** [comment]
Ok, I understand what you are experiencing, but I am totally clueless as to how you got there. In other words, I need more info.

1. How did you create the VHD?
2. What version of NitrOS9 are you using?
3. What version of "format" did you use?
4. What exactly is your "boot creation" process? Include step by step, with any tools used for each step
5. Any other info you can think of that would help.

This will help me recreate what you are doing so I can see what is going on.
Thanks,
Bill P.

**Comment by pahandav** [comment]
1. Download the VHD Files and Install Disks.zip in one my posts above this, it's got everything I'm using for this in it.
2. The *latest* development sources. The latest upstream update to the sources was committed last Tuesday.
3. Whichever version of format is included in the latest sources.
4. Again, refer to the zip file.
5. I can't think of anything else to say, it's better to just go through the instructions in the zip file. Honestly, this isn't that big of a problem. I can make VHDs in this manner in version 2.1.0b and below, so it shouldn't cause significant problems for anyone else following my instructions.

**Comment by ejaquay** [comment]
My experience is that it works.  I am able to format and copy files to
newly created vhds and was able to create a rgbdos vhd using the patched
version of Vcc.   Are you sure you are using the right Vcc version?

[image: Untitled.png]

**Comment by pahandav** [comment]
I think I figured out the problem on my end. On a whim, I tried the beta executable with the 2.1.0b .dlls, and it worked. Of course, only one drive could be selected. So, long story short, I realized that the hard drive code is contained in the harddisk.dll file, which I don't have. In other words, right .exe version, wrong .dll version.

**Comment by ejaquay** [comment]
My brain must have malfunctioned.  To test fix the new version of harddrive.dll is required.  The version of vcc.exe probably does not actually matter. 

https://github.com/ejaquay/VCC/releases/download/harddisk-fix/vcc-harddisk.zip

**Comment by pahandav** [comment]
I tested it again, and everything is working fine with the updated harddisk.dll. I can install NitrOS-9, copy other files to the drive, format a second drive (even though I didn't bother with the RS-DOS partitions for that), and copy files to that, and between the drives. You can probably close this issue as fixed. Thanks.

**Comment by ejaquay** [comment]
Use the vcc.exe and harddisk.dll from this zip file for testing.
https://github.com/ejaquay/VCC/releases/download/harddisk-fix/vcc-harddisk.zip

**Comment by ejaquay** [comment]
You need the new harddrive.dll for the patch to work!

**Comment by ejaquay** [comment]
I had tried to follow the instructions and they worked mostly.   After
running the create tool I had to go back to Nitros9 and do a DSAVE again
because the tool deleted the Nitros9 files. After that every thing seems
okay
.
